# Generated by Django 5.1.1 on 2024-10-14 06:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('adina', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('gaixotasuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('mediku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Osakidetza.mediku')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Osakidetza.paziente')),
            ],
        ),
    ]
